name: AplikasiPelanggan
description: Aplikasi untuk pelanggan.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.0
  supabase_flutter: ^2.9.1
  go_router: ^16.1.0
  flutter_dotenv: ^5.1.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1  # Pastikan versi ini

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app_icon.png

flutter_launcher_icons:  # SEJAJAR dengan 'dependencies' dan 'flutter'
  android: true
  ios: false
  image_path: "assets/app_icon.png"